# Docker compose used to bring up dev environment

services:

  nginx:
    container_name: woj-nginx
    image: nginx:alpine
    ports:
      - '9000:80'
    volumes:
      - ./.docker/nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - $IMAGES_DIRECTORY:/var/www/html:ro
