# Docker compose used to bring up dev environment

services:

  postgres:
    container_name: woj-postgres
    image: postgres:latest
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: woj

  nginx:
    container_name: woj-nginx
    image: nginx:alpine
    ports:
      - '9000:80'
    volumes:
      - ./.docker/nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - $IMAGES_DIRECTORY:/var/www/html:ro
