# Docker compose used to bring up dev environment

services:

  postgres:
    container_name: woj-postgres
    image: postgres:latest
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: woj

  minio:
    container_name: woj-minio
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./.docker/data/minio:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: woj